# target: dependencies
# <tab> rule

# make (without arguments) executes first rule in file
# Ideally, one target for every object file and a target for final binary. 

yash: main.c
	gcc -g -o yash main.c 

clean:
	rm *.o yash
